// Entirely fictional towns. Names built from genuine northern place-name parts
// (-thwaite, -garth, -clough, -gill, -royd, -forth...) so they could pass on an OS map.
// The facts, however, are nonsense. Any resemblance to real places is a failure of
// imagination on reality's part.
window.FAKE_TOWNS = [
  // Plausible veterans
  {name:"Scraggthwaite", blurb:"Scraggthwaite does not exist, which is a shame, because its annual Scrag End Festival — three days of celebrating the worst cut of lamb — deserves at least a segment on Countryfile."},
  {name:"Clagholme", blurb:"Entirely made up. Had it been real, Clagholme would have been famous for mud so adhesive that wellies are handed down through families still attached to the original owner."},
  {name:"Wamblethorpe", blurb:"Does not exist. In the timeline where it does, Wamblethorpe's one-way system is so confusing that three delivery drivers from 1987 are still in it."},
  {name:"Fettlesworth", blurb:"Invented. A pity — Fettlesworth's motto, 'It'll Fettle', would have been the most honest civic slogan in England, and its repair shop could fix owt but your attitude."},
  {name:"Gruntley Bridge", blurb:"Not real. The bridge in question would have been a single plank over a beck, maintained since 1743 by a rota of men who communicate exclusively in nods."},
  {name:"Mitherley", blurb:"Invented. 'Mithering' is real dialect for pestering, and Mitherley would have been founded by people who moved to the moors specifically to get away from everyone, then complained it was quiet."},
  {name:"Trubshaw Bottom", blurb:"Fictional. Trubshaw Bottom would have spent two centuries campaigning to be renamed and one afternoon a year secretly enjoying the coach parties."},
  {name:"Parkinstall", blurb:"Does not exist, though parkin — the sticky ginger cake — very much does. Parkinstall would have been the only town with a cake-based economy and a dentist with a yacht."},
  {name:"Bleakmires", blurb:"Fictional. Bleakmires would have been twinned with nowhere, by mutual agreement."},
  {name:"Cinderclough", blurb:"Fictional. A clough is a real ravine, cinders are real regret, and Cinderclough would have combined both with a viaduct to nowhere that won architectural awards for menace."},
  {name:"Muckleforth", blurb:"Not real. Muckleforth's ford would have claimed a tractor a year, and the town would have kept a leaderboard."},
  {name:"Hoyleclough", blurb:"Made up. Hoyleclough would have been built entirely on a 45-degree slope, with the post office at the top and everyone's letters at the bottom."},
  {name:"Crumbleden", blurb:"Made up. Crumbleden would have been the rhubarb crumble capital of the north, locked in a decades-long custard cold war with a village it refuses to name."},
  {name:"Backley Bottoms", blurb:"Not real. Backley Bottoms would have appeared on novelty postcards since 1904 without ever technically existing, making it the north's most photographed fictional settlement."},
  {name:"Hackthwaite", blurb:"Invented. Hackthwaite's imaginary claim to fame — 'probably where coughing was invented' — would have been disputed by historians and supported by everyone who's lived through a Pennine January."},
  {name:"Puddlebrough", blurb:"Does not exist. Puddlebrough's marina would have been a puddle of genuinely impressive size, with moorings."},
  {name:"Threppleton", blurb:"Fictional. Threppleton would have had a market charter from 1288 and a market consisting, since 1971, of one van selling batteries."},
  {name:"Soggarth", blurb:"Not real. Soggarth would have been the only town with an official towel exchange, and its cricket team would have never once completed a home fixture."},
  {name:"Gritstall", blurb:"Made up. Gritstall would have supplied the grit for every northern road and personality, mined from a quarry the town describes as 'character-building' and the council describes as 'a liability'."},
  {name:"Mardleforth", blurb:"Not real. Mardleforth — from 'mardy', meaning sulky — would have declared itself independent in 1976 after a dispute about bin day, and be technically still not speaking to England."},
  {name:"Whinberley", blurb:"Invented, though whinberries are real Pennine bilberries. Whinberley's pickers would have guarded their moorland patches with a secrecy MI5 once asked to study."},
  {name:"Slutchley", blurb:"Does not exist. 'Slutch' is genuine Lancashire for deep mud, and Slutchley would have been the only town where wellies count as formalwear, including at weddings."},
  {name:"Brassholme", blurb:"Not real. Brassholme would have had where there's muck, and consequently claimed to have brass, though audits consistently found only muck."},
  {name:"Cobbleworth", blurb:"Invented. Cobbleworth's streets would have been cobbled, then tarmacked in 1968, then expensively re-cobbled in 2009 for a period drama that filmed elsewhere."},
  {name:"Tattersgill", blurb:"Does not exist. Tattersgill's imaginary potato festival would have crowned a King Edward every autumn in a ceremony older and more solemn than most coronations."},
  {name:"Ironthwaite", blurb:"Fictional. Ironthwaite would have made the iron for something genuinely famous, lost the paperwork, and spent 150 years saying 'well it was us' at dinner parties."},
  {name:"Cragbottom", blurb:"Invented. Cragbottom would have sat directly beneath a crag that geologists described as 'due', and estate agents described as 'characterful'."},
  {name:"Haarby", blurb:"Made up, though 'haar' is the real north-east sea fog. Haarby would have been visible from the sea roughly twice a year, both times a disappointment."},
  {name:"Lugworth", blurb:"Fictional. Lugworth's imaginary annual general meeting would have lasted eleven hours, entirely composed of matters arising from the previous eleven-hour meeting."},
  {name:"Pettibridge", blurb:"Made up. Pettibridge's two halves would have feuded for 200 years over which side of the bridge the town hall faces. The town hall would have burned down in 1930, resolving nothing."},
  {name:"Threapworth", blurb:"Fictional. 'Threap' is real dialect for arguing stubbornly, and Threapworth's parish council would have been in continuous session since 1894, currently on agenda item two."},
  {name:"Laikthorpe", blurb:"Invented. 'Laik' is real Yorkshire for play, and Laikthorpe would have been the only town where the mills shut for wet playtime."},
  {name:"Ozzlethwaite", blurb:"Fictional. Ozzlethwaite would have feuded with Oswaldtwistle for a century over which was the original Ozzy, a dispute complicated by Ozzlethwaite not existing."},
  {name:"Puthergill", blurb:"Not real. Puthergill's gill would have puthered — a real word for billowing smoke — continuously since the 1820s, from a source no inspector ever located and no local ever disclosed."},
  {name:"Wutherstone", blurb:"Not real. Wutherstone would have been so windswept that the Brontës considered setting a novel there but found it 'a bit much'."},
  {name:"Nithergate", blurb:"Does not exist. 'Nithered' is real dialect for being perishing cold, and Nithergate would have been the street where the wind waited for you, personally, by name."},
  {name:"Gormsley", blurb:"Made up. Gormsley — as in 'gormless', but aspirational — would have commissioned a giant rusty statue on the moors and called it the Angel of the Nowt."},
  {name:"Ratchdale", blurb:"Invented. Ratchdale would have been Rochdale's forgotten cousin, mentioned only at family funerals and left nothing in the will."},
  {name:"Trundleforth", blurb:"Fictional. Trundleforth's bypass would have opened in 1974 and been immediately bypassed by a bigger bypass, leaving the town twice-forgotten — a national record."},
  {name:"Mistlebrough", blurb:"Fictional. Mistlebrough would have appeared on maps only in certain weather, like a civic Brigadoon with a retail park."},
  {name:"Eckersby", blurb:"Invented. Eckersby's imaginary town crier retired in 1962 and was never replaced because, as the parish minutes record, 'everyone already knows everything'."},
  {name:"Clartmoor", blurb:"Fictional, though 'clarty' is real north-eastern for filthy-muddy. Clartmoor's imaginary agricultural show would have been cancelled 61 consecutive years due to ground conditions, and held anyway."},
  {name:"Sniddlethwaite", blurb:"Does not exist, though 'sniddle' is genuine old Lancashire for coarse marsh grass. Sniddlethwaite would have exported sniddle to a world that never once ordered any."},

  // Plausible newcomers, nonsensical facts
  {name:"Harthwaite", blurb:"Does not exist. Records would have shown Harthwaite twinned with itself since 1953, an administrative error both parties have repeatedly refused to correct."},
  {name:"Gledholme", blurb:"Fictional. Gledholme's clocks would have run eight minutes behind the rest of England following a referendum, with a hardline faction still campaigning for twelve."},
  {name:"Wexforth", blurb:"Made up. Wexforth's tide would have come in overland, across two fields and a bowling green, and the town would have long since stopped finding this remarkable."},
  {name:"Aldercleugh", blurb:"Not real. Aldercleugh's parish boundary would have been redrawn annually according to the movements of one specific eel, a system its residents defend as 'fairer than Westminster'."},
  {name:"Birkgarth", blurb:"Invented. Every street in Birkgarth would have been named after the same man, including both Ernest Street and Upper Ernest Street, and nobody now would remember what Ernest did."},
  {name:"Thackerdale", blurb:"Does not exist. Thackerdale's census would have counted everyone twice 'to be safe', making it officially the fastest-growing town in Europe with a population of nought."},
  {name:"Whinstall", blurb:"Fictional. Whinstall's bus timetable would have been an oral tradition, passed from driver to driver, and the 8:40 would have been more of a story than a service."},
  {name:"Ravensgill", blurb:"Made up. In Ravensgill, ravens would have had right of way, motorists second, and pedestrians by appointment only, bookable at the library on Tuesdays."},
  {name:"Storthwick", blurb:"Not real. Storthwick would have banned the wheelbarrow in 1911 for reasons never recorded, and the ban would remain in force purely because repealing it means admitting nobody knows."},
  {name:"Hazelgarth", blurb:"Invented. Hazelgarth's village green would have been legally classified as a hedge since a surveying dispute in 1904, and cricket would be played inside it."},
  {name:"Owsthwaite", blurb:"Does not exist. Owsthwaite would have had four accepted pronunciations, all of them wrong, with the correct one dying with a Mrs Ackroyd in 1958."},
  {name:"Embleforth", blurb:"Fictional. Embleforth's war memorial would have listed everyone who came back as well, on the grounds that they'd been through enough without being left off a list."},
  {name:"Farnclough", blurb:"Made up. Farnclough's chapel and pub would have shared one building, one door, and one strict rule about which side of it you told people you'd been on."},
  {name:"Bramforth", blurb:"Not real. Bramforth's one-way system would have predated the motor car by 60 years, having originally been introduced to manage an aggressive goose."},
  {name:"Keldbrough", blurb:"Invented. Keldbrough Castle would have been demolished in 1809 to improve the view of where the castle used to be, a decision the town would still describe as 'ahead of its time'."},
  {name:"Scarthby", blurb:"Does not exist. Scarthby's beck would have run uphill on Thursdays, a phenomenon blamed variously on the moon, the quarry, and a family it's better not to name."},
  {name:"Ulvergill", blurb:"Fictional. Ulvergill would have claimed the last wolf in England was shot there — in 1997, by the postmistress, an incident the parish newsletter covered in four lines."},
  {name:"Wrayholme", blurb:"Made up. Wrayholme's cricket pitch would have sat on a one-in-four slope, with deep fine leg roped to the pavilion and the follow-on enforced by gravity."},
  {name:"Stainscar", blurb:"Not real. Stainscar's quarry would have produced stone exclusively for other towns' war memorials and civic statues, leaving Stainscar itself commemorated by a bench."},
  {name:"Rudsworth", blurb:"Invented. Rudsworth's allotment waiting list would have stood at 214 years, with plots bequeathed in wills and at least one contested at appeal by a ghost."},
  {name:"Caldergate", blurb:"Does not exist. Caldergate's high street would have flooded on a published schedule, listed in the parish newsletter under 'Events', with a raffle."},
  {name:"Aikenshaw", blurb:"Fictional. Aikenshaw's maypole would have been taken down in 1951 for safety reasons and replaced with a sign describing the maypole, around which children now dance."},
  {name:"Ortley", blurb:"Made up. 'Orts' are real dialect for leftover scraps, and Ortley would have been built entirely out of materials other towns didn't finish, including half a viaduct and most of a town hall."},
  {name:"Hutterby", blurb:"Not real. Hutterby's phone box would have been Grade II listed in 1988, with the phone itself removed for being too modern."},
  {name:"Gressenholme", blurb:"Invented. At Gressenholme parish meetings, geese would have counted toward the quorum since 1832, and on at least two occasions carried the vote."},
  {name:"Crosedale", blurb:"Does not exist. Crosedale would have had two churches of the same denomination, ninety yards apart, not speaking since 1873 over a matter involving a harmonium."},
  {name:"Witherclough", blurb:"Fictional. Sunlight would have reached the floor of Witherclough twice a year, and both occasions would be bank holidays, with bunting."},
  {name:"Hebbleroyd", blurb:"Made up. Hebbleroyd would have had forty-four looms, three surnames, and a genealogy society that meets in secret for everyone's safety."},
  {name:"Sowdenshaw", blurb:"Not real. Sowdenshaw Brass would have placed second at the Nationals in 1926, and the town would still be pursuing the matter through what it calls 'the proper channels'."},
  {name:"Oxengarth", blurb:"Invented. Oxengarth's annual ox roast would have run continuously since 1704, adding a vegetarian option in 2019: a smaller ox."},
  {name:"Salterfell", blurb:"Does not exist. Salterfell's packhorse road would have been so steep the horses went up backwards, a technique the town would have taught at evening classes until 1961."},
  {name:"Tarnbrough", blurb:"Fictional. Tarnbrough's tarn would have been declared officially bottomless by a 1911 survey team who ran out of rope, patience, and daylight, in that order."},
  {name:"Rookstall", blurb:"Made up. Rookstall's rookery would have held the freehold of the church since a paperwork error in 1743, collecting rent in a manner the diocese describes as 'ongoing'."},
  {name:"Stangforth", blurb:"Not real. Stangforth's ford would have been measurably deeper than the river it crossed, a paradox the county surveyor visited once and never spoke of again."},
  {name:"Yockenden", blurb:"Invented. Yockenden's dialect would have been so localised it was spoken fluently in only one house, and the family weren't telling anyone what the words meant."},
  {name:"Dunscarth", blurb:"Does not exist. Dunscarth's sundial would have been famously wrong, and corrected in 1889 by the addition of a second sundial, which is also wrong, but differently."},
  {name:"Marlgarth", blurb:"Fictional. Marlgarth's clay pit would have produced marl so fine that potters wept openly, and would have been closed in 1902 'for sentimental reasons'."},
  {name:"Loftgill", blurb:"Made up. Loftgill would have had the highest post box in England, serviced by rope, with second-class post going up on a fortnightly basis, weather and nerve permitting."},
  {name:"Gatesholme", blurb:"Not real. Gatesholme would have had seventeen listed gates and no fences, each gate opened and shut daily by a warden out of what the town calls 'respect'."},
  {name:"Ewsley", blurb:"Invented. The 1974 Ewsley sheepdog trials would have ended in a draw with the sheep, a result the Kennel Club refuses to recognise and the sheep never mention."},
  {name:"Padforth", blurb:"Does not exist. Padforth's footpath network would have been ninety times longer than its road network, with several paths leading confidently into the side of a hill."},
  {name:"Cawthwaite", blurb:"Fictional. Cawthwaite's school register would have been taken by a crow since 1922, with absences reported directly to mothers before the child got home."},
  {name:"Dringholme", blurb:"Made up. Dringholme would have kept its Viking name and, until surprisingly recently, its Viking — the last one leaving for Whitby in 1974 over a planning matter."},
  {name:"Thrangby", blurb:"Not real. 'Thrang' is genuine dialect for busy, and Thrangby would have never once been busy, a streak of quiet stretching back, unbroken, to the Domesday Book."},
  {name:"Micklegarth", blurb:"Invented. 'Mickle' means much, and Micklegarth would have had little, a discrepancy the tourist board addressed with the slogan 'Micklegarth: More Than You'd Think', which there isn't."},
  {name:"Ganderclough", blurb:"Does not exist. Ganderclough's goose fair would have been cancelled permanently in 1937 following what contemporary reports call 'a coordinated action' by the geese."},
  {name:"Slackholme", blurb:"Fictional. 'Slack' is real northern for a hollow, and Slackholme would have sat in one so complete that radio arrived a day late and weather a day early."},
  {name:"Sourby", blurb:"Made up. Sourby's rhubarb would have been grown in total darkness and harvested by candlelight, like the real Rhubarb Triangle's, except Sourby's rhubarb allegedly hummed."},
  {name:"Blegdale", blurb:"Not real. Blegdale would have been the only dale in Yorkshire with no river, keeping one on standby in a reservoir 'in case of inspection'."},
  {name:"Murkholme", blurb:"Invented. Murkholme's streetlights would have been switched on in 1932 and off in 1933 after a ratepayers' revolt, and the matter would be considered closed."},
  {name:"Fothergarth", blurb:"Does not exist. Fothergarth's hay — 'fother' being real dialect for fodder — would have won so many rosettes that the hay, not the farmer, was invited to open the 1957 county show."},
  {name:"Nettlegarth", blurb:"Fictional. Nettlegarth's nettle-eating championship would have been described by its oldest competitor as 'older than the nettle itself', a claim botanists decline to engage with."},
  {name:"Ribbleforth", blurb:"Made up. Ribbleforth's bridge toll would have been one piece of gossip per crossing, payable to the keeper, making the toll house the best-informed building in Lancashire."},
  {name:"Aireholme", blurb:"Not real. Aireholme's houseboats would have outnumbered its houses two to one, with the mayor residing on a coal barge called Persistence."},
  {name:"Wharfegill", blurb:"Invented. Wharfegill's stepping stones would have been spaced for a stride no recorded human possesses, and the parish would have minuted this as 'a matter for walkers'."},
  {name:"Cuthworth", blurb:"Does not exist. Cuthworth's church would have venerated a toe of St Cuthbert of uncertain provenance, drawing pilgrims, sceptics, and one very patient chiropodist."},
  {name:"Ellerforth", blurb:"Fictional. Ellerforth's elderflower wine would have been licensed as both a beverage and a paint stripper, with the vicar's batch classified separately under maritime law."}
];
